#lang racket/base
(provide (all-defined-out))

(struct varsub (varname step)#:prefab)
(struct vecsub (varname step)#:prefab)
(struct assignment(leftvar rightexpr)#:prefab)
(struct  vcallassignment(leftvar rightexpr)#:prefab)
(struct funcall(f explist)#:prefab)
(struct exprforname(expr) #:prefab)
(struct divide (left right)#:prefab)
(struct add (left right)#:prefab)
(struct addmany (lst)#:prefab)
(struct times (left right)#:prefab)
(struct difffuncsub (step)#:prefab)
(struct shortname (id step)#:prefab)